package io.github.mathpalnaman.hinglishprofanity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Stream;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * The Java detector must return exactly what the JavaScript build returns.
 *
 * <p>test/fixtures/parity.json is generated by scripts/gen-parity.mjs from the
 * built JS package: every corpus input plus test/fixtures/parity-inputs.txt,
 * each run under every option set. This test replays all of it and compares
 * score, cleaned text, and every field of every match, in order.
 */
class ParityTest {

  /**
   * Inputs whose result differs ONLY because Java 17 ships Unicode 13 tables
   * and the Node version in .nvmrc ships Unicode 16. Each entry names the
   * character and what differs. Listed individually, never by category.
   *
   * <p>So far the difference is confined to `cleaned`, so an excluded input is
   * not skipped: its matches and score are still compared, and only the
   * `cleaned` comparison is inverted (it must differ, or the entry is stale).
   */
  private static final Map<String, String> JAVA_UNICODE_EXCLUSIONS =
      Map.of(
          // U+A7C0 LATIN CAPITAL LETTER OLD POLISH O, added in Unicode 14 (Lu).
          // Node: a letter, lowercased to U+A7C1 and kept, so cleaned is
          // "fuckꟁfuck" and the input is one token. Java 17: unassigned,
          // so it is a separator and cleaned is "fuckfuck". The two `fuck`
          // matches themselves are identical.
          "fuckꟀfuck", "U+A7C0 is a letter in Unicode 14+, unassigned in 13",
          // U+11F02 KAWI SIGN REPHA, added in Unicode 15 (Lo). Node keeps it in
          // cleaned as a one-character token; Java 17 drops it as a separator.
          // Both report the same two `lund` matches.
          "lund 𑼂 lund", "U+11F02 is a letter in Unicode 15+, unassigned in 13");

  private static final JsonNode PARITY = Fixtures.readJson("test/fixtures/parity.json");

  /** Detectors are immutable, so one per option set serves every input. */
  private static final Map<String, Detector> DETECTORS = new ConcurrentHashMap<>();

  private static Detector detector(JsonNode options) {
    return DETECTORS.computeIfAbsent(options.toString(), key -> Fixtures.detectorFor(options));
  }

  static Stream<Arguments> cases() {
    List<Arguments> out = new ArrayList<>();
    JsonNode optionSets = PARITY.get("optionSets");

    for (JsonNode entry : PARITY.get("inputs")) {
      String input = entry.get("input").asText();
      for (int i = 0; i < optionSets.size(); i++) {
        JsonNode run = entry.get("runs").get(i);
        out.add(
            Arguments.of(
                "opt" + i + " " + Fixtures.printable(input),
                input,
                optionSets.get(i),
                run.get("score").asDouble(),
                run.get("matches"),
                entry.get("cleaned").asText()));
      }
    }

    int n = 0;
    for (JsonNode c : PARITY.get("cases")) {
      String input = c.get("input").asText();
      JsonNode result = c.get("result");
      out.add(
          Arguments.of(
              "corpus-options" + (n++) + " " + Fixtures.printable(input),
              input,
              c.get("options"),
              result.get("score").asDouble(),
              result.get("matches"),
              result.get("cleaned").asText()));
    }
    return out.stream();
  }

  /** Renders matches in the JSON shape the JS package returns, field for field. */
  static ArrayNode toJson(List<Match> matches) {
    ArrayNode array = Fixtures.JSON.createArrayNode();
    for (Match m : matches) {
      ObjectNode node = array.addObject();
      node.put("term", m.term());
      node.put("matchedText", m.matchedText());
      node.put("index", m.index());
      node.put("endIndex", m.endIndex());
      node.put("severity", m.severity());
      node.put("confidence", m.confidence().jsValue());
      node.put("method", m.method().jsValue());
      node.put("lang", m.lang());
    }
    return array;
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("cases")
  void matchesJavaScript(
      String name, String input, JsonNode options, double score, JsonNode matches, String cleaned) {
    Result result = detector(options).detect(input);

    String excluded = JAVA_UNICODE_EXCLUSIONS.get(input);
    if (excluded == null) {
      assertEquals(cleaned, result.cleaned(), "cleaned");
    } else {
      assertNotEquals(cleaned, result.cleaned(), "stale exclusion, delete it: " + excluded);
    }
    assertEquals(matches, toJson(result.matches()), "matches");
    assertEquals(score, result.score(), 1e-9, "score");
  }
}
